language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t rualoguh/frontend -f Dockerfile.dev . 

script:
 - docker run  -e CI=true rualoguh/frontend npm run test
 